<?php

namespace TN\TOEICTrainerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocQuestionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocQuestionsRepository extends EntityRepository
{
}
