<?php

namespace TN\TOEICTrainerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PictureFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureFileRepository extends EntityRepository
{
}
